import "./globals.css";

import type { Metadata } from "next";
import { Croissant_One } from "next/font/google";

import Providers from "./providers";

const font = Croissant_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <title>Lista de Presentes · Vitória & André</title>
        <meta
          property="twitter:title"
          content="Lista de Presentes · Vitória & André"
        />
        <meta
          property="og:title"
          content="Lista de Presentes · Vitória & André"
        />
        <meta property="twitter:image" content="/thumbnail.png" />
        <meta property="og:image" content="/thumbnail.png" />
      </head>
      <body className={`bg-beige text-wine ${font.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
